### ISSUE TITLE
Why the earth ended up being a sphere?

### ISSUE THREAD

**Issue by edupenabad** [jonblower/hazards-lab#12]
There are some issues related to the "sphericity" of the earth and the implications of longitude being a periodic variable, mainly affecting:

- Resampling (higher temporal frequency) of original data. Script needs to be improved on that
- Storing and displaying features that crosses the longitude boundary (0/360 or -180/180)

**Comment by edupenabad** [comment]
Problems in resampling data and features crossing borders has been solved:

- Adequate resampling when crossing the -180/180 boundary
- Validity checks on the geometries within the database bootstrap script

**Comment by jonblower** [comment]
That's great that you've solved this! Can you include (either here or in the docs) some info on how you solved it?

**Comment by edupenabad** [comment]
I hope to be able to include some info on that in the final documents...

On 21/10/15 17:02, Jon Blower wrote:
>
> That's great that you've solved this! Can you include (either here or 
> in the docs) some info on how you solved it?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jonblower/hazards-lab/issues/12#issuecomment-149943966>.
>

-- 
*Eduardo Penabad Ramos *|Senior Software Developer, Institute for 
Environmental Analytics
Philip Lyle Building, University of Reading, Whiteknights Campus, 
Reading RG6 6BX
*T:*+44(0)118 378 6821 *E:*e.penabad-ramos@the-iea.org 
<mailto:e.penabad-ramos@the-iea.org>*W:*www.the-iea.org 
<http://www.the-iea.org/>
